# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 207)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.trend_line_CB = QtWidgets.QComboBox(self.frame_2)
        self.trend_line_CB.setObjectName("trend_line_CB")
        self.trend_line_CB.addItem("")
        self.trend_line_CB.addItem("")
        self.horizontalLayout.addWidget(self.trend_line_CB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.watersaturated_CB = QtWidgets.QComboBox(self.frame_2)
        self.watersaturated_CB.setObjectName("watersaturated_CB")
        self.watersaturated_CB.addItem("")
        self.watersaturated_CB.addItem("")
        self.horizontalLayout_3.addWidget(self.watersaturated_CB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.legend_CB = QtWidgets.QCheckBox(self.frame_2)
        self.legend_CB.setObjectName("legend_CB")
        self.verticalLayout_2.addWidget(self.legend_CB)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.test_frame = QtWidgets.QFrame(self.centralwidget)
        self.test_frame.setEnabled(False)
        self.test_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_frame.setObjectName("test_frame")
        self.testButton_1 = QtWidgets.QPushButton(self.test_frame)
        self.testButton_1.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.testButton_1.setObjectName("testButton_1")
        self.testButton_2 = QtWidgets.QPushButton(self.test_frame)
        self.testButton_2.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.testButton_2.setObjectName("testButton_2")
        self.verticalLayout.addWidget(self.test_frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Линия тренда"))
        self.trend_line_CB.setItemText(0, _translate("MainWindow", "exp"))
        self.trend_line_CB.setItemText(1, _translate("MainWindow", "line"))
        self.label_2.setText(_translate("MainWindow", "Водонасыщенность"))
        self.watersaturated_CB.setItemText(0, _translate("MainWindow", "current"))
        self.watersaturated_CB.setItemText(1, _translate("MainWindow", "residual"))
        self.legend_CB.setText(_translate("MainWindow", "Легенда графика"))
        self.testButton_1.setText(_translate("MainWindow", "PushButton"))
        self.testButton_2.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
